### ISSUE TITLE
Package issue

### ISSUE THREAD

**Issue by OkonSamuel** [macd/Varpro.jl#1]
I want to find out if this package work in Julia v0.7 alpha.

**Comment by macd** [comment]
Yes, it works (only) on v0.7 alpha with the new package manager.  You will need to also install NL2sol.
Both will need to be cloned from github by using the develop command, ie
julia>  <now type ']'>
(v0.7) pkg> develop https://github.com/macd/NL2sol.jl
(v0.7) pkg> develop https://github.com/macd/Varpro.jl

etc,
