### ISSUE TITLE
Differing conventions as compared to Matlab Varpro

### ISSUE THREAD

**Issue by xecej4** [macd/Varpro.jl#2]
The reported values of some of the results from the Julia version of Varpro differ from the results from the Matlab version of Varpro at https://www.cs.umd.edu/~oleary/software/varpro/ . I observed this after applying both versions to the Lanczos2 test problem at https://www.itl.nist.gov/div898/strd/nls/data/LINKS/v-lanczos2.shtml . The differences are as follows:

Norm-squared of weighted residual:  (1/2) of expected result
Norm of weighted residual              :  sqrt(1/2) of expected result
Expected error of observations        :  sqrt(1/2) of expected result

I suspect that the reason is that NL2SOL minimizes F(x) = **half** of the residual sum of squares at x.

Please clarify. Thanks!

**Comment by macd** [comment]
From the comments in the file https://github.com/macd/NL2sol.f/src/nl2sol.f we see
```
c  ***  purpose  ***
c
c        given a p-vector x of parameters, calcr computes an n-vector
c     r = r(x) of residuals corresponding to x.  (r(x) probably arises
c     from a nonlinear model involving p parameters and n observations.)
c     this routine interacts with nl2itr to seek a parameter vector x
c     that minimizes the sum of the squares of (the components of) r(x),
c     i.e., that minimizes the sum-of-squares function
c     f(x) = (r(x)**t) * r(x) / 2.  r(x) is assumed to be a twice con-
c     tinuously differentiable function of x.
c
```
so, yes NL2sol defines the sum of the residuals to be  (r' * r)/2  This does point out that the README.md for Varpro.jl did not contain any information or pointers to NL2sol and I have updated the README.md accordingly. Thanks for the feedback.
